// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'apiKey': string;
  'apiKeyAction': string;
  'apiKeyValue': string;
  'email': string;
  'role': string;
  'user': string;
  'username': string;
}
export const cssExports: CssExports;
export default cssExports;
