// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addUser': string;
  'apiKey': string;
  'email': string;
  'role': string;
  'username': string;
  'usersHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
