// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'pageIndicator': string;
  'pdfCanvas': string;
  'reader': string;
  'rendering': string;
  'sidebar': string;
  'sidebarDelete': string;
  'sidebarHeader': string;
  'sidebarItem': string;
  'sidebarItemEmpty': string;
  'sidebarList': string;
  'sidebarSection': string;
  'toolbar': string;
  'toolbarButton': string;
  'viewer': string;
}
export const cssExports: CssExports;
export default cssExports;
